# Generated by Django 4.2.17 on 2025-02-08 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookchat', '0003_remove_book_like_book_liked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='poster',
            field=models.URLField(max_length=500),
        ),
    ]
