# Generated by Django 4.2.17 on 2025-02-08 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookchat', '0005_comment_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parent',
            new_name='parent_id',
        ),
    ]
