# Generated by Django 4.2.17 on 2025-02-08 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookchat', '0006_rename_parent_comment_parent_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
